title: Gl체hweintour
url: https://www.gluehweintour.de
description: "Gesellige Gl체hweintouren in und um M체nchen"
lang: de_DE
author: Manuel Sch채chinger
author: Ignaz Schlennert
permalink: /:year-:title

plugins:
  - jekyll-seo-tag

ga: UA-35956463-2

markdown: kramdown

defaults:
  - scope:
      path: "."
      type: "drafts"
    values:
      sitemap: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

sass:
  style: compressed
